NeonGeckoCom/neon_enclosure

requirements/requirements.txt, version.py
Update neon_utils dependency to use PyPI
Increment version
=> Update neon-utils dependency

neon_enclosure/client/enclosure/base.py
Remove GUI class and LOG depreciation notice for methods moved to neon_core.gui
=> Handle relocation of gui service to NeonCore

Dockerfile, README.md, requirements/requirements.txt
Fix dockerfile errors
Update Docker documentation
=> Docker Implementation Improvements

neon_enclosure/__main__.py, neon_enclosure/service.py
Handle loading plugins if one fails
Implement Neon wrapper class with extra logging
=> Fix PHAL init

.github/workflows/license_tests.yml, tests/license_tests.py
=> Add license tests with automation

LICENSE.md, setup.py
Update license spec in setup.py
=> Add LICENSE.md

neon_enclosure/__main__.py, neon_enclosure/service.py, requirements/requirements.txt
Init `enclosure` log on module start
Update log references to neon_utils
=> Update log handling

README.md, neon_enclosure/admin/__init__.py, neon_enclosure/admin/__main__.py, neon_enclosure/admin/service.py, requirements/requirements.txt, tests/test_enclosure_service.py
Implement admin enclosure service with unit tests and updated documentation
=> Admin Enclosure Service

.github/workflows/license_tests.yml, .github/workflows/publish_release.yml, .github/workflows/publish_test_build.yml, .github/workflows/pull_master.yml, .github/workflows/unit_tests.yml
Update GitHub automations to used shared workflows from .github repository
=> Update automation to shared repository

requirements/requirements.txt
Add ovos-core dependency to resolve issue with Docker container
=> Add ovos-core dependency for mycroft.util dependency

version.py
=> Increment version to 1.3.0

requirements/docker.txt, requirements/requirements.txt
Remove ovos-utils patching
Update docker plugins to stable versions
=> Update dependencies to stable versions

neon_enclosure/__main__.py, neon_enclosure/admin/__main__.py, neon_enclosure/admin/service.py, neon_enclosure/service.py, requirements/requirements.txt, requirements/test_requirements.txt, tests/test_enclosure_service.py
Cleanup dependencies to remove ovos-core dep and neon-messagebus test dep
=> Simplify Dependencies

.github/workflows/publish_test_build.yml, requirements/requirements.txt
Update stable dependencies
Update automation to publish prereleases
=> Prep stable release

.github/workflows/publish_test_build.yml
Fix release automation
Fix refactor from #60
=> Fix alpha release automation change

.github/workflows/license_tests.yml, .github/workflows/unit_tests.yml
Updates automation triggers to ensure PR's to master have required workflow runs
=> Update automation to run license and unit tests on PR to 'master' branch

neon_enclosure/__main__.py, neon_enclosure/admin/__main__.py
=> Add optional malloc logging to service

neon_enclosure/admin/__main__.py, neon_enclosure/cli.py, setup.py
Implement CLI with config init refactor
=> Implement CLI and move config init to CLI entrypoint

neon_enclosure/__main__.py, neon_enclosure/admin/__main__.py, neon_enclosure/cli.py, requirements/requirements.txt, tests/test_enclosure_service.py
Adds unit test coverage for CLI entrypoints
=> Add unit tests for CLI methods

requirements/requirements.txt, tests/test_enclosure_service.py
Update neon_utils dependency to stable version
=> Stable dependencies

neon_enclosure/__main__.py, neon_enclosure/admin/__main__.py
=> Add `skill_id` to services to resolve logged deprecation warnings

neon_enclosure/__main__.py, neon_enclosure/admin/__main__.py, neon_enclosure/admin/service.py, neon_enclosure/service.py
Support passed kwargs with good defaults for `bus` and `skill_id`
=> Better handle default init kwargs

Dockerfile
Update XDG_CONFIG_HOME default path for k8s compat.
=> Kubernetes container compat.

requirements/docker.txt
=> Add monitoring plugin to docker dependencies

requirements/docker.txt
=> Update plugins to stable releases

Dockerfile, docker_overlay/root/run.sh, neon_enclosure/cli.py, neon_enclosure/utils.py, requirements/requirements.txt
- Expand the entrypoint with an additional command, "install-dependencies" command
Closes #84
=> feature: expands entry point to install dependencies from extra_dependencies config

requirements/docker.txt, requirements/requirements.txt
Update dependencies to prep for release
=> Update dependencies to stable and pinned alpha versions
